# Generated by Django 4.2 on 2023-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_auto_20230408_0841"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
