# Generated by Django 4.2 on 2023-04-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_alter_comment_replies_alter_comment_reply_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
